### PR TITLE
lower jtag freq

### PR DESCRIPTION
**Pull request by erikdanie**

### CODE REVIEW

**Review by sifivekevin — APPROVED** [review]
LGTM

**Comment by bsousi5** [comment]
@paul-walmsley-sifive have you created all the necessary branch for llama release yet?
This PR is also needed for llama, but should be a merge point after the current Llama GR RC1 hash.

**Comment by erikdanie** [comment]
I'm not sure this needs a separate branch, I think master and llama point to the same commit right now

**Comment by paul-walmsley-sifive** [comment]
~~master and release_generator_llama don't point to the same commit, so Erik, you'll need to do a separate PR against release_generator_llama if you want it on Llama~~

Never mind, this only applies to freedom-e-sdk-private

**Pull request merged**
