### PR TITLE
lower vcu118 jtag freq to safer 1.8M

### PR DESCRIPTION
**Pull request by erikdanie**

### CODE REVIEW

**Review by ernie-sifive — APPROVED** [review]
We need a faster JTAG solution, but this is the best we can do for now.

**Review by nategraff-sifive — APPROVED** [review]
You should also PR this against v20.05-branch

**Comment by erikdanie** [comment]
Ah, sorry, didn't realize there was one

**Comment by erikdanie** [comment]
That PR is here: https://github.com/sifive/openocdcfg-generator/pull/15

**Pull request merged**
